// Gallery name patterns by country/region
export const galleryNamePatterns: Record<string, string[]> = {
  // Europa
  'Italia': [
    '{city} Arte Contemporanea',
    'Galleria {city}',
    'Spazio {city}',
    'Studio d\'Arte {city}',
    '{city} Arte Moderna',
    'Fondazione {city}',
    'Arte {city}',
    'Galleria Moderna {city}',
    '{city} Contemporanea',
    'Nuovo Spazio {city}'
  ],
  'Francia': [
    'Galerie {city}',
    'Espace d\'Art {city}',
    'Centre d\'Art {city}',
    '{city} Art Contemporain',
    'Atelier {city}',
    'Fondation {city}',
    'Espace {city}',
    'L\'Art de {city}',
    'Le Studio {city}',
    '{city} Espace Créatif'
  ],
  'Germania': [
    '{city} Galerie',
    'Kunsthalle {city}',
    'Kunstverein {city}',
    '{city} Kunsthaus',
    '{city} Contemporary',
    'Kunst Raum {city}',
    'Projektraum {city}',
    '{city} Kunst',
    'Studio {city}',
    'Neue Kunst {city}'
  ],
  'Regno Unito': [
    '{city} Gallery',
    '{city} Art Space',
    '{city} Contemporary',
    'The {city} Art Gallery',
    '{city} Studio',
    '{city} Arts',
    'Art House {city}',
    'New Art {city}',
    '{city} Project Space',
    '{city} Modern'
  ],
  'Spagna': [
    'Galería {city}',
    'Espacio de Arte {city}',
    '{city} Arte Contemporáneo',
    'Fundación {city}',
    'Centro de Arte {city}',
    '{city} Contemporánea',
    'Espacio {city}',
    'Arte {city}',
    'Taller {city}',
    '{city} Estudio'
  ],
  'Paesi Bassi': [
    '{city} Galerie',
    'Kunsthuis {city}',
    '{city} Art Space',
    'Studio {city}',
    '{city} Contemporary',
    'Kunst {city}',
    '{city} Modern',
    'Nieuwe Kunst {city}',
    '{city} Project',
    'Artspace {city}'
  ],
  'Europa dell\'Est': [
    '{city} Gallery',
    '{city} Art Center',
    'Contemporary {city}',
    'Art Space {city}',
    '{city} Studio',
    'Modern Art {city}',
    '{city} Exhibition Space',
    'Art {city}',
    '{city} Project',
    'Cultural Space {city}'
  ],
  'Scandinavia': [
    '{city} Konsthall',
    '{city} Galleri',
    'Kunst {city}',
    '{city} Art Center',
    '{city} Contemporary',
    'Studio {city}',
    '{city} Project Space',
    'Galleri {city}',
    '{city} Modern',
    '{city} Kunsthalle'
  ],

  // Asia Pacifico
  'Giappone': [
    '{city} Art Space',
    '{city} Gallery',
    '{city} Contemporary Art',
    'Studio {city}',
    '{city} Art Project',
    '{city} Modern Art',
    '{city} Art Lab',
    '{city} Art Center',
    '{city} Exhibition Space',
    '{city} Foundation'
  ],
  'Cina': [
    '{city} Art Gallery',
    '{city} Contemporary',
    '{city} Art Center',
    '{city} Modern Art',
    '{city} Art Space',
    '{city} Art Project',
    '{city} Studio',
    '{city} Art Museum',
    '{city} Art Foundation',
    '{city} Creative Space'
  ],
  'Corea del Sud': [
    '{city} Art Space',
    '{city} Gallery',
    '{city} Contemporary',
    '{city} Art Center',
    '{city} Project Space',
    '{city} Art Foundation',
    '{city} Studio',
    '{city} Art Lab',
    '{city} Modern Art',
    '{city} Creative'
  ],
  'Sud Est Asiatico': [
    '{city} Art Space',
    '{city} Gallery',
    '{city} Contemporary',
    '{city} Art Center',
    '{city} Modern',
    '{city} Art Project',
    '{city} Studio',
    '{city} Creative Hub',
    '{city} Art Lab',
    '{city} Exhibition Space'
  ],
  'Australia e Oceania': [
    '{city} Gallery',
    '{city} Contemporary',
    '{city} Art Space',
    '{city} Art Project',
    '{city} Studio',
    '{city} Modern',
    '{city} Art Center',
    '{city} Creative Space',
    '{city} Art House',
    '{city} Arts'
  ],

  // Americhe
  'Stati Uniti': [
    '{city} Gallery',
    '{city} Contemporary',
    '{city} Art Space',
    '{city} Studio',
    '{city} Project Space',
    '{city} Modern',
    '{city} Art Center',
    '{city} Arts',
    '{city} Foundation',
    '{city} Art Lab'
  ],
  'Canada': [
    '{city} Gallery',
    '{city} Art Center',
    '{city} Contemporary',
    '{city} Art Space',
    '{city} Studio',
    '{city} Arts',
    '{city} Modern',
    '{city} Project Space',
    '{city} Art Lab',
    '{city} Foundation'
  ],
  'America Latina': [
    'Galería {city}',
    'Espacio de Arte {city}',
    '{city} Arte Contemporáneo',
    'Centro Cultural {city}',
    '{city} Contemporánea',
    'Fundación {city}',
    'Espacio {city}',
    'Arte {city}',
    '{city} Estudio',
    '{city} Proyecto'
  ],

  // Africa e Medio Oriente
  'Africa': [
    '{city} Art Space',
    '{city} Gallery',
    '{city} Contemporary',
    '{city} Art Center',
    '{city} Art Project',
    '{city} Art Foundation',
    '{city} Studio',
    '{city} Cultural Center',
    '{city} Art Hub',
    '{city} Creative Space'
  ],
  'Medio Oriente': [
    '{city} Gallery',
    '{city} Art Space',
    '{city} Contemporary',
    '{city} Art Center',
    '{city} Modern Art',
    '{city} Foundation',
    '{city} Studio',
    '{city} Art Project',
    '{city} Art Lab',
    '{city} Art House'
  ]
};

// List of specializations that galleries can have
export const specializations = [
  'Arte Contemporanea',
  'Fotografia',
  'Scultura',
  'Installazioni',
  'Video Art',
  'Performance Art',
  'Street Art',
  'Arte Digitale',
  'Pittura',
  'Mixed Media',
  'Arte Concettuale',
  'Arte Tessile',
  'Arte Sonora',
  'Nuovi Media',
  'Grafica',
  'Arte Urbana',
  'Arte Ambientale',
  'Arte Interattiva',
  'Disegno',
  'Ceramica',
  'Arte Femminista',
  'Arte Politica',
  'Arti Performative',
  'Design',
  'Architettura',
  'Virtual Reality Art',
  'Bio Art',
  'Net Art',
  'Light Art',
  'Arte Cinetiche',
  'Tradizione e Contemporaneità',
  'Arte Indigena',
  'Arte Post-coloniale',
  'Arte Africana Contemporanea',
  'Arte Asiatica Contemporanea',
  'Arte Latino-americana',
  'Arte Medio Orientale',
  'Arte Pubblica',
  'Interventi Urbani',
  'Arte Relazionale'
];

// Generic gallery descriptions
export const galleryDescriptions = [
  'Galleria specializzata in {specialization} con focus su artisti emergenti {region}.',
  'Spazio dedicato alla {specialization}, con particolare attenzione alle nuove generazioni di artisti {region}.',
  'Centro d\'arte contemporanea con focus su {specialization} da artisti emergenti {region}.',
  'Galleria che presenta il lavoro di artisti {region} emergenti, con particolare attenzione alla {specialization}.',
  'Spazio alternativo che esplora la {specialization} nel contesto {region}.',
  'Piattaforma dedicata agli artisti emergenti {region} che lavorano con {specialization}.',
  'Galleria che promuove la {specialization} attraverso mostre ed eventi con artisti {region} emergenti.',
  'Spazio creativo che supporta e valorizza la {specialization} di artisti emergenti {region}.',
  'Centro espositivo dedicato alla {specialization} con un programma che valorizza artisti emergenti {region}.',
  'Galleria che si concentra sulla {specialization}, con un\'attenzione particolare al dialogo tra tradizione e innovazione {region}.',
  'Spazio dedicato a promuovere la {specialization} di artisti emergenti, con particolare attenzione alle pratiche {region}.',
  'Galleria con un programma espositivo incentrato sulla {specialization}, valorizzando le voci artistiche emergenti {region}.',
  'Centro d\'arte che promuove il dialogo interculturale attraverso la {specialization} di artisti emergenti {region}.',
  'Spazio espositivo che esplora le potenzialità della {specialization} nel panorama artistico emergente {region}.',
  'Galleria che presenta una selezione curata di {specialization} da talenti emergenti {region}.'
];

// Region adjectives for descriptions
export const regionAdjectives: Record<string, string> = {
  'Italia': 'italiani',
  'Giappone': 'giapponesi',
  'Germania': 'tedeschi',
  'Stati Uniti': 'americani',
  'Corea del Sud': 'coreani',
  'Francia': 'francesi',
  'Regno Unito': 'britannici',
  'Spagna': 'spagnoli',
  'Cina': 'cinesi',
  'Australia': 'australiani',
  'Brasile': 'brasiliani',
  'Canada': 'canadesi',
  'Messico': 'messicani',
  'Paesi Bassi': 'olandesi',
  'Belgio': 'belgi',
  'Svizzera': 'svizzeri',
  'Austria': 'austriaci',
  'Portogallo': 'portoghesi',
  'Grecia': 'greci',
  'Polonia': 'polacchi',
  'Repubblica Ceca': 'cechi',
  'Ungheria': 'ungheresi',
  'Romania': 'rumeni',
  'Croazia': 'croati',
  'Slovenia': 'sloveni',
  'Estonia': 'estoni',
  'Lettonia': 'lettoni',
  'Lituania': 'lituani',
  'Finlandia': 'finlandesi',
  'Svezia': 'svedesi',
  'Norvegia': 'norvegesi',
  'Danimarca': 'danesi',
  'India': 'indiani',
  'Tailandia': 'tailandesi',
  'Vietnam': 'vietnamiti',
  'Malaysia': 'malesi',
  'Singapore': 'singaporiani',
  'Indonesia': 'indonesiani',
  'Filippine': 'filippini',
  'Nuova Zelanda': 'neozelandesi',
  'Taiwan': 'taiwanesi',
  'Hong Kong': 'di Hong Kong',
  'Argentina': 'argentini',
  'Cile': 'cileni',
  'Colombia': 'colombiani',
  'Perù': 'peruviani',
  'Venezuela': 'venezuelani',
  'Ecuador': 'ecuadoriani',
  'Uruguay': 'uruguaiani',
  'Bolivia': 'boliviani',
  'Sud Africa': 'sudafricani',
  'Nigeria': 'nigeriani',
  'Kenya': 'kenioti',
  'Marocco': 'marocchini',
  'Egitto': 'egiziani',
  'Ghana': 'ghanesi',
  'Senegal': 'senegalesi',
  'Tunisia': 'tunisini',
  'Emirati Arabi Uniti': 'emiratini',
  'Israele': 'israeliani',
  'Libano': 'libanesi',
  'Turchia': 'turchi',
  'Iran': 'iraniani'
};